language: node_js
os:
  - linux
node_js:
  - "lts/*"

before_install:
  - |
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache: npm

script:
  - npm run lint
  - npm run compile
  - npm run test

before_deploy:
  - npm install -g vsce
  - vsce package

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_ACCESS_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: felixjb/testify
      tags: true
  - provider: script
    script: vsce publish -p $VSCE_MKT_PLACE_ACCESS_TOKEN
    skip_cleanup: true
    on:
      repo: felixjb/testify
      branch: master
      tags: true
